// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/openmodu/cloak/internal/repo/confrepo"
	"github.com/openmodu/cloak/internal/repo/langrepo"
	"github.com/openmodu/cloak/internal/repo/regexrepo"
	"github.com/openmodu/cloak/internal/transport/http"
	"github.com/openmodu/cloak/internal/usecase/restorer"
)

// Injectors from wire.go:

// InitApp 装配脱敏/还原两条流水线，CLI 与测试用它。
func InitApp(cfg Config) (*App, error) {
	v, err := regexrepo.NewDefaultSet()
	if err != nil {
		return nil, err
	}
	v2, err := ProvideNERRecognizers(cfg)
	if err != nil {
		return nil, err
	}
	v3 := ProvideRecognizers(v, v2)
	detector := langrepo.New()
	memory := confrepo.NewDefault()
	masker := ProvideMasker(v3, detector, memory, cfg)
	restorerRestorer := restorer.New()
	app := NewApp(masker, restorerRestorer, memory)
	return app, nil
}

// InitServer 在此之上装配 HTTP 服务，cloakd 用它。
func InitServer(cfg Config) (*http.Server, error) {
	v, err := regexrepo.NewDefaultSet()
	if err != nil {
		return nil, err
	}
	v2, err := ProvideNERRecognizers(cfg)
	if err != nil {
		return nil, err
	}
	v3 := ProvideRecognizers(v, v2)
	detector := langrepo.New()
	memory := confrepo.NewDefault()
	masker := ProvideMasker(v3, detector, memory, cfg)
	restorerRestorer := restorer.New()
	app := NewApp(masker, restorerRestorer, memory)
	llmClient, err := ProvideLLMClient(cfg)
	if err != nil {
		return nil, err
	}
	proxy := ProvideProxy(masker, restorerRestorer, llmClient)
	server := ProvideHTTPServer(app, proxy, cfg)
	return server, nil
}
